### ISSUE TITLE
Version being set to x.y.z

### ISSUE THREAD

**Issue by asmeurer** [ergs/rever#15]
I am using $VERSION and it is is being set to x.y.z instead of the version I am passing in.

**Comment by asmeurer** [comment]
FYI this is a major blocker for me right now.

**Comment by asmeurer** [comment]
I think it is only being defined inside an @activity. So I have to do some stupid workarounds to make it defined at the module level.

**Comment by scopatz** [comment]
Under what circumstances are you seeing this? Is there a way to reproduce.

If you are using the CLI, the argparser requires that version be set on the command line and then it very quicly sets $VERSION [(see here)](https://github.com/ergs/rever/blob/master/rever/main.xsh#L139)

x.y.z is the default env var value [(see here)](https://github.com/ergs/rever/blob/master/rever/environ.xsh#L76) but you should never see this once environ.context() is entered... i.e. in `env_main()`

**Comment by asmeurer** [comment]
It seems to happen when I use $VERSION outside of an @activity. I need to define it at the module level so that I can access it in some helper functions.

**Comment by scopatz** [comment]
outside of an activity in rever.xsh? Or in a test file? or where exactly?  Sorry I am not seeing it :(

**Comment by asmeurer** [comment]
In rever.xsh. I tried setting

```
version = $VERSION
```

at the module level of the file, and it gets set to `x.y.z`.

**Comment by scopatz** [comment]
That is definitely a bug =/

**Comment by scopatz** [comment]
OK I have a test that reproduces this bug.

**Comment by scopatz** [comment]
See #23
