### ISSUE TITLE
Rever runs git reset?

### ISSUE THREAD

**Issue by asmeurer** [ergs/rever#17]
When I run rever, it seems to reset the changes I make to rever.xsh.

**Comment by asmeurer** [comment]
Can we make the default behavior not do anything with git? And the fact that the default behavior runs destructive git commands is especially bad.

**Comment by scopatz** [comment]
> When I run rever, it seems to reset the changes I make to rever.xsh

That is bad!

> Can we make the default behavior not do anything with git? And the fact that the default behavior runs destructive git commands is especially bad.

Yes, we can and should.  I think the easy way to do this is to add a do-nothing git/hg/svn alias to the aliases mapping on entering the environment. This will mask git everywhere unless someone is really trying get to these tools (via `which -s` or an absolute path)

**Comment by asmeurer** [comment]
I mean [this line](https://github.com/ergs/rever/blob/07d8a660813e5b212cd386df13999135fc67f7b6/rever/activity.xsh#L81) should not be there. It should only be there if you explicitly want it to do that. 

I've been running Rever in a docker container, so these features don't really matter to me (everything runs from scratch every time I run it). Except when I need to test things locally, this causes annoyances. This and the fact that rever won't rerun an activity that it thinks has finished (should it include the hash of `rever.xsh` so that changing it causes it to re-run?).

**Comment by scopatz** [comment]
Well, when you undo you are explicitly asking for a rewind. However, the rewind it likely affecting too many files.

Including the hash/version of rever in the log is a good idea.
