### ISSUE TITLE
Use Doctr to build/deploy docs

### ISSUE THREAD

**Issue by CJ-Wright** [ergs/rever#27]
Is there any interest in using Doctr to build/deploy the docs? I noticed that the web docs have not been updated recently (they still note xonsh as the development target).

**Comment by scopatz** [comment]
Yes, there is absolutely interest in doing this.

**Comment by CJ-Wright** [comment]
Do you still want it on ergs?

**Comment by scopatz** [comment]
As opposed to having its own org?

**Comment by CJ-Wright** [comment]
No, currently the webdocs are on your group website, I don't know how to doctr that

**Comment by scopatz** [comment]
Oh that is easy, we deploy to other repos all the time.  The docs are hosted on github still.

**Comment by scopatz** [comment]
We just have a CNAME setup from USC to github

**Comment by CJ-Wright** [comment]
Cool.

**Comment by scopatz** [comment]
Yeah, Also, I just added the rever-docs repo to the members team, with admin permisions. You should have access to it now.
